# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeIV <- function(xi, H, eta, rho, T, K, N, M, seed, num_threads) {
    .Call('RBergomi_computeIV', PACKAGE = 'RBergomi', xi, H, eta, rho, T, K, N, M, seed, num_threads)
}

computeIV_RT <- function(xi, H, eta, rho, T, K, N, M, seed, num_threads) {
    .Call('RBergomi_computeIV_RT', PACKAGE = 'RBergomi', xi, H, eta, rho, T, K, N, M, seed, num_threads)
}

