// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// computeIV
DataFrame computeIV(double xi, NumericVector H, NumericVector eta, NumericVector rho, NumericVector T, NumericVector K, int N, long M, IntegerVector seed, int num_threads);
RcppExport SEXP RBergomi_computeIV(SEXP xiSEXP, SEXP HSEXP, SEXP etaSEXP, SEXP rhoSEXP, SEXP TSEXP, SEXP KSEXP, SEXP NSEXP, SEXP MSEXP, SEXP seedSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type H(HSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< long >::type M(MSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(computeIV(xi, H, eta, rho, T, K, N, M, seed, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// computeIV_RT
DataFrame computeIV_RT(double xi, NumericVector H, NumericVector eta, NumericVector rho, NumericVector T, NumericVector K, int N, long M, IntegerVector seed, int num_threads);
RcppExport SEXP RBergomi_computeIV_RT(SEXP xiSEXP, SEXP HSEXP, SEXP etaSEXP, SEXP rhoSEXP, SEXP TSEXP, SEXP KSEXP, SEXP NSEXP, SEXP MSEXP, SEXP seedSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type H(HSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T(TSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< long >::type M(MSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(computeIV_RT(xi, H, eta, rho, T, K, N, M, seed, num_threads));
    return rcpp_result_gen;
END_RCPP
}
